name: Plugin Compile Test

on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read 

jobs:
  build:
    name: Plugin Compile Test
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew && chmod +x *.sh

      # Build  (Debug)
      - name: Compile Debug
        run: sh compileDebug.sh
        
      # Upload plugin artifacts
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: output/*.zip
